version: "3.9"

services:
  db:
    image: postgres:latest
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/fastapi/app
    image: fastapi-app:dev
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
